COMMENT ON TABLE parcel is 'from intersection-spandex parcels';
COMMENT ON TABLE parcel_invalid is 'from intersection';
COMMENT ON TABLE parcel_geometrycollection is 'from intersection-';
COMMENT ON TABLE parcel_valid is 'from intersection-valid subset of spandex parcels';
COMMENT ON TABLE zoning.lookup_valid is 'from intersection-subset of zoning.merged_jurisdictions with valid geometries';
COMMENT ON TABLE zoning.parcel_intersection_count is 'from intersection-st_intersects of parcel and zoning';
COMMENT ON TABLE zoning.parcels_with_multiple_zoning is 'from intersection-';
COMMENT ON TABLE zoning.parcels_with_one_zone is 'from intersection-';
COMMENT ON TABLE zoning.parcel is 'from intersection-final parcel/zoning table';
COMMENT ON TABLE zoning.parcel_overlaps is 'from intersection-area calculations for parcels in several zoning geoms';
COMMENT ON TABLE zoning.parcel_overlaps_maxonly  is 'from intersection-inserted in final table';
COMMENT ON TABLE zoning.parcel_two_max is 'from intersection-';
COMMENT ON TABLE zoning.parcel_counties is 'from intersection-';
COMMENT ON TABLE zoning.parcel_cities_counties is 'from intersection-';
COMMENT ON TABLE zoning.parcel_in_cities is 'from intersection-';
COMMENT ON TABLE zoning.parcel_two_max_not_in_cities is 'from intersection-';
COMMENT ON TABLE zoning.parcel_in_counties is 'from intersection-';
COMMENT ON TABLE zoning.temp_parcel_county_table is 'from intersection-';
COMMENT ON TABLE zoning.parcels_in_multiple_cities is 'from intersection-';
COMMENT ON TABLE zoning.parcels_in_multiple_counties is 'from intersection-';
COMMENT ON TABLE zoning.parcel_two_max_geo is 'from intersection-';
COMMENT ON TABLE zoning.parcel_two_max_geo_overlaps is 'from intersection-';
--output a table with geographic information and generic code info for review
COMMENT ON TABLE zoning.parcel_withdetails is 'from intersection-';
COMMENT ON TABLE zoning.parcel_two_max_geo is 'from intersection-';
COMMENT ON TABLE zoning.unmapped_parcels is 'from intersection-';
COMMENT ON TABLE zoning.unmapped_parcel_zoning is 'from intersection-';
